config/routes.rb
Onwebacc::Application.routes.draw do
  get "report/show"

  get "taxes/new"

  get "infos/new"

  
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match 'microposts/local_sales', to: 'microposts#local_sales', as: :local_sales
  match 'microposts/interstate_sales', to: 'microposts#interstate_sales', as: :interstate_sales
  resources :microposts, only: [:show, :create, :destroy,:index]
  resources :infos  
  resources :taxes
  get "customers/upload"
  resources :customers do
    collection {post :import}
  end
  resources :categories 
  resources :deliverables
  get "products/upload"

  resources :products  do
    collection { post :import }
  end


  
  
  root to: 'static_pages#home'
  
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete 
 
  match '/help', to:'static_pages#help'
  match '/about', to:'static_pages#about'
  match '/contact', to:'static_pages#contact'











end

app/views/shared/_bill.html.erb
<div id="error-holder"></div>

<div class="appear">
  <div id ="cust-form">
    <%= render 'shared/customer_formtastic'%>
  </div>
  <div id="flr"><button id = "hide_customer" class="btn btn-info">Hide </button></div>
<br>

</div>

<div id="bill-form">
  <%= simple_form_for @micropost ,:html => {:class => "form-inline"} do |f| %>

      <div class="row" id="carouselSection_invoice">
        <br/>
        <div class="span3"><%= f.input :invoice_number  %></div>
        <div class="span3"><%= f.input :bill_date,as: :date_picker %></div>
        <div class="span4 dropdown">
          <%= f.input :customer,
                      :as => :select,
                      :collection =>Hash[current_user.customers.all.map{ |p| [p.name+ " -- " + p.tin ,p.id] }] ,
                      :include_blank => false
          %>
        </div>
      </div>
      <br/>


      <%= f.simple_fields_for :deliverables do |d| %>
          <%= render 'shared/deliverable_fields', :f => d %>
      <% end %>

      <p><%= link_to_add_fields "Add", f, :deliverables %></p>

      <div class="row" id="carouselSection_tax">
        <br/>
        <%= f.simple_fields_for :infos do |i| %>
            <div class="span11">
              <div class="row">
                <div class="span4"><%= i.input :tax_id, :as => :select,:collection =>Hash[current_user.taxes.all.map{ |t| [t.state + " --- " + t.rate.to_s + "%",t.id]}] , :label => "Tax",:include_blank => false %></div>

                <div class="span3"><%= i.input :sur_name, :label  => "Name Other Charges (if any) ",:input_html => {:id => 'suggested'}%></div>
                <div class="span3"><%= i.input :sur_tax, :label => "Other Charge Rate (if any) ",:input_html => {:title => 'this is a lumpsum charge and is not percentage based'}%></div>
                <br/>
              </div>
            </div>

            <div class="span11">
              <div class="row">
                <div class="span10">
                  <%= i.input :gen_info, :label => "Other Information To Be Printed on The Bill",:input_html => {:rows => 2}%>
                </div>
              </div>
            </div>
        <% end %>
      </div>
      <br/>
      <br/>


      <%= f.submit "Continue", :class => "btn btn-primary"  %>

  <% end %>

</div>

app/views/shared/_cat_entry.html.erb
<p>Please enter both name and code for the commodity</p>
	<%= semantic_form_for @category, :remote=>true , :html => {:id => 'cc' } do |f| %>
	<%= f.inputs  :name => "Commodity"  ,:class =>"form-input" ,:input_html => {:title => 'ensure both name and code are identical to that in the ESugam website '} do %>
     <%= f.input :name%>
     <%= f.input :main_code, :label => "Main Commodity Code"%>
     <%= f.input :sub_code, :label => "Sub Commodity Code" %>
     <% end %>

	<%= f.action :submit,:button_html => { :class => "btn btn-small"} %>
	<% end %>

app/views/shared/_cat_list.html.erb

<h4 class="center"> Commodities  </h4>
<% if @cat_feed_list.any? %>

<ol class="microposts">
	<%= render partial: 'shared/category_el', collection: @cat_feed_list %>
</ol>

<% end %>

app/views/shared/_category_el.html.erb
<li id="<%= category_el.id %>">

	<span class="user">
	<h5> Commodity Name :<%= category_el.name %></h5>	
	<h5>Main Commodity code :	<%= category_el.main_code %></h5>
	<h5>Sub Commodity code :	<%= category_el.sub_code %></h5>
	<p>
		
	</p>
	<p><%= link_to "edit",edit_category_path(category_el),:remote => true, class: "btn btn-info" %> </p>
	</span>
</li>

app/views/shared/_d_product.html.erb

<div class="dialog-form">
	
<%= render 'shared/product_entry' %>

</div>

app/views/shared/_del_list_show.html.erb
<% @total = 0 %>
<% @tax = 0%>
<% @sur_tax = 0 %>








<% @taxis = Tax.find(@info.tax_id) %>
<% if @del_items.any? %>

    <table  class="table">
      <tr>
        <th><h4> Product name  </h4></th>
        <th><h4> Quantity  </h4></th>
        <th><h4> Unit Price  </h4></th>
        <th><h4> Amount  </h4></th>
      </tr>


      <%= render partial: 'shared/del_item_show.html.erb', collection: @del_items %>

    </table>



    <h4> Total = <%= @total %> </h4>
    <% if @info.sur_name != "" && @info.sur_tax != nil %>
        <h4> <%= @info.sur_name %> = <%= @info.sur_tax.to_s %> </h4>
        <%@total += @info.sur_tax %>
    <% end %>
    <% @tax = (@total * @taxis.rate * 0.01).round(2) %>
    <h4> <%= @taxis.state%> @ <%= @taxis.rate.to_s %> %  on <%= @total %> = <%= @tax %></h4>
    <h4> Grand total = <%= @total+@tax %></h4>
    <h4> Other information = <%= @info.gen_info %></h4>
    <br>

    <%= link_to 'Create PDF ', micropost_path(@micropost, :format => :pdf),:target => "_blank" ,:class=>"btn" %>
    <%= link_to "tally xml",micropost_path(@micropost,:format => :xml),{:class=>"btn"} %>
    <% if @bill.esugam == nil %>
        <%= link_to "Generate e-sugam",micropost_path(@micropost, :cause => "esn"),{:class=>"btn",:id=>"spinneret", confirm: "IF you want to cancel the esugam number you will have to do it in the vat website within 48 hours . Do you want to continue ?"} %>
    <% end %>

<% end %>


<div id="spinme"></div>
<div id=messpin><h4>please wait for the esugam number to be generated , thank you , this can take upto a minute !</h4> </div>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="microposts">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<% if feed_item != nil %>
    <li id="<%= feed_item.id %> ">

      <% @deliverables = feed_item.deliverables.all %>

      <% if @deliverables.first != nil && feed_item.infos.first != nil %>
          <% @product = Product.find(@deliverables.first.product_id )%>




          <span class="content"><b><%=link_to  @product.name , feed_item  %></b>
		<b><%= feed_item.bill_date %></b>
	</span>

          <% if feed_item.unedit != true %>
              <h4><%= feed_item.customer.name %> </h4>
          <% else %>
              <h4> Cash Transaction </h4>
          <% end %>
          <% if feed_item.category != nil %>
              <h4><<%= feed_item.category.name %>/h4>
          <% end %>
          <span class="timestamp">
		Posted <%= time_ago_in_words(feed_item.created_at )%> ago.
	</span>
          <% if current_user?(feed_item.user) and feed_item.esugam == nil %>
              <h4> </h4>
          <%else%>
              <h4><%= feed_item.esugam %><% end %></h4>
      <% end %>
    </li>
<% end %>	

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
		<%= f.text_area :content, placeholder: "Compose new micropost ..." %>
	</div>
	<%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_product_entry.html.erb
<%= semantic_form_for @product, :remote=>true , :html => {:id => 'pc' } do |f|  %>
	<%= f.semantic_errors :state %>
	<%= f.inputs :name,:unit, :name => "product" %>
	<%= f.input :description, :as=> :select, :collection => Hash[current_user.categories.all.map{|p| [p.name,p.name]}],:include_blank => false %>
	
	<%= f.action :submit, :button_html => {:class => "btn"} %>
<% end %>

app/views/shared/_script_upd_cust.js.erb
<script>
$(function(){
	$(".tryout").empty();
	alert("please work");
});
	
</script>

app/views/shared/_tax_edit.html.erb
<%= semantic_form_for @tax, :remote=>true , :html => {:id => 'tc' } do |f| %>
	<%= f.input :state,:as => :radio,:collection => ["VAT","CST"], :name => "tax"  %>
	<%= f.input :rate %>
	<%= f.action :submit,:button_html => { :class => "btn btn-small"} %>
	<% end %>

app/views/shared/_tax_el.html.erb
<li id="<%= tax_el.id %>">

	<span class="user">
	<h5> Tax Type  : <%= tax_el.state %></h5>	
	<h5>Tax Rate :	<%= tax_el.rate %> %</h5>
	<p>
		
	</p>
	<p><%= link_to "edit",edit_tax_path(tax_el),:remote => true, class: "btn btn-info" %> </p>
	</span>
</li>